@echo off
cd Scripts

BIOS.bat
exit && start BOOTCONFIG.bat
exit && start CDROM.bat
exit && start COMPUTERSYSTEM.bat
exit && start CSPRODUCT.bat
exit && start DATAFILE.bat
exit && start DCOMAPP.bat
exit && start DESKTOP.bat
exit && start DESKTOPMONITOR.bat
exit && start DEVICEMEMORYADDRESS.bat
exit && start DISKQUOTA.bat
exit && start DMACHANNEL.bat
exit && start ENVIRONMENT.bat
exit && start FSDIR.bat
exit && start GROUP.bat
exit && start IDECONTROLLER.bat
exit && start IRQ.bat
exit && start JOB.bat
exit && start LOADORDER.bat
exit && start LOGICALDISK.bat 
exit && start MEMCACHE.bat
exit && start MEMORYCHIP.bat
exit && start MEMPHYSICAL.bat
exit && start motherboard.bat
exit && start NETCLIENT.bat
exit && start NETLOGIN.bat
exit && start NETPROTOCOL.bat
exit && start NETUSE.bat
exit && start NIC.bat
exit && start NICCONFIG.bat
exit && start NTDOMAIN.bat
exit && start NTEVENT.bat
exit && start NTEVENTLOG.bat
exit && start ONBOARDDEVICE.bat
exit && start OS.bat
exit && start PAGEFILE.bat
exit && start PAGEFILESET.bat
exit && start PARTITION.bat
exit && start PORT.bat
exit && start PORTCONNECTOR.bat
exit && start PRINTER.bat
exit && start PRINTERCONFIG.bat
exit && start PRINTJOB.bat
exit && start PROCESS.bat
exit && start PRODUCT.bat
exit && start QFE.bat
exit && start QUOTASETTING.bat
exit && start RDACCOUNT.bat
exit && start RDNIC.bat
exit && start RDPERMISSIONS.bat
exit && start RDTOGGLE.bat
exit && startRECOVEROS.bat
exit && start REGISTRY.bat
exit && start SCSICONTROLLER.bat
exit && start SERVER.bat
exit && start SERVICE.bat
exit && start SHADOWCOPY.bat
exit && start SHADOWSTORAGE..bat
exit && start SHARE.bat
exit && start SOFTWAREELEMENT.bat
exit && start SOFTWAREFEATURE.bat
exit && start SOUNDDEV.bat
exit && start STARTUP.bat
exit && start SYSACCOUNT.bat
exit && start SYSDRIVER.bat
exit && start SYSTEMENCLOSURE.bat
exit && start SYSTEMSLOT.bat
exit && start TAPEDRIVE.bat
exit && start TEMPERATURE.bat
exit && start TIMEZONE.bat
exit && start UPS.bat
exit && start USERACCOUNT.bat
exit && start VOLTAGE.bat
exit && start VOLUME.bat
exit && start VOLUMEQUOTASETTING.bat
exit && start VOLUMEUSERQUOTA.bat
exit && start WMISET.bat
